# Usa una imagen base de Python
FROM python:3.8

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo 'app.py', 'requirements.txt', y la carpeta 'templates'
COPY app.py /app/
COPY templates /app/templates/
COPY requirements.txt /app/

# Instala las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto 5000
EXPOSE 5000

# Define el comando por defecto para ejecutar tu aplicación
CMD ["python", "app.py"]
